# This software is the exclusive property of Gencovery SAS.
# The use and distribution of this software is prohibited without the prior consent of Gencovery SAS.
# About us: https://gencovery.com


from gws_core import (BarPlotView, BoxPlotView, ConfigParams, File, Folder,
                      IntParam, LinePlot2DView, MultiViews, StackedBarPlotView,
                      StrParam, StrRField, Table, TableImporter,
                      resource_decorator, view)
from gws_core.extra import TableBoxPlotView, TableView


@resource_decorator("Qiime2SampleFrequenciesFolder", human_name="Qiime2 sample frequencies folder",
                    short_description="Folder containing files generated by the Qiime2 sample frequencies analysis",
                    hide=True, deprecated_since='0.2.1',
                    deprecated_message='Please use Qiime2FeatureFrequencyFolder instead')
class Qiime2SampleFrequenciesFolder(Folder):
    ''' Qiime2SampleFrequenciesFolder Folder file class '''

    sample_frequency_file_path: str = StrRField()  # ''

    @view(view_type=TableView,
          human_name='Frequency table',
          short_description='Table of sample frequencies', default_view=True)
    def view_as_table(self, params: ConfigParams) -> TableView:
        table: Table
        file_path = self.get_sub_path("sample-frequency-detail.tsv")
        table = TableImporter.call(File(path=file_path), {'delimiter': 'tab', "index_column": 0})
        table_view = TableView(table=table)
        table_view.set_title("Sample frequency values")
        data = table.get_data()
        median = data.median(axis=0).iat[0]
        average = data.mean(axis=0).iat[0]
        table_view.set_caption(
            f"For the following step, using close to median value is advised (ref).\nMedian: {median}, average: {average} ")
        return TableView(table=table)

    @view(view_type=BoxPlotView, human_name='Frequency boxplot',
          short_description='Boxplot view of of sample frequencies')
    def view_as_boxplot(self, params: ConfigParams) -> BoxPlotView:
        table: Table
        file_path = self.get_sub_path("sample-frequency-detail.tsv")
        table = TableImporter.call(File(path=file_path), {'delimiter': 'tab', "index_column": 0})
        table_view = TableView(table=table)
        table_view.set_title("Sample frequency values")
        bx_view = BoxPlotView()
        data = table.get_data()
        bx_view.add_data(data=data)
        return bx_view
