# This software is the exclusive property of Gencovery SAS.
# The use and distribution of this software is prohibited without the prior consent of Gencovery SAS.
# About us: https://gencovery.com


from gws_core import Folder, resource_decorator


@resource_decorator("Qiime2FeatureFrequencyFolder", human_name="Qiime2 feature frequency folder",
                    short_description="Folder containing files generated by the Qiime2 feature table extractors",
                    hide=True, deprecated_since='0.2.5',
                    deprecated_message='Use simple folder instead')
class Qiime2FeatureFrequencyFolder(Folder):
    """ Qiime2FeatureFrequencyFolder Folder file class """
